[project]
name = "ist409"
version = "0.1.0"
description = "lab for ist409"
readme = "README.md"
authors = [
    { name = "Karma Dorji", email = "karmad84@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "darts>=0.46.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
    "tensorflow>=2.21.0",
]

[project.scripts]
ist409 = "ist409:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
